# Generated by Django 2.0.7 on 2018-07-20 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=128, unique=True)),
                ('date', models.CharField(max_length=128)),
                ('fpath', models.CharField(max_length=256)),
                ('uname', models.CharField(max_length=128)),
            ],
        ),
    ]
