# Generated by Django 2.0.7 on 2018-08-10 06:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('dept', models.CharField(max_length=128)),
                ('job', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=64)),
                ('phone', models.CharField(max_length=64)),
                ('power', models.IntegerField(default=1)),
                ('hirdate', models.DateTimeField(default=datetime.datetime(2018, 8, 10, 6, 1, 9, 685245, tzinfo=utc))),
            ],
        ),
    ]
