# Generated by Django 2.0.7 on 2018-08-10 06:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='hirdate',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 10, 6, 1, 44, 75554, tzinfo=utc)),
        ),
    ]
