# Generated by Django 2.0.7 on 2018-07-24 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='power',
            field=models.IntegerField(default=1),
        ),
    ]
