# Generated by Django 2.0.7 on 2018-08-01 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_power'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dept',
            field=models.CharField(default='研发部', max_length=128),
        ),
        migrations.AddField(
            model_name='user',
            name='job',
            field=models.CharField(default='python开发', max_length=128),
        ),
    ]
