# Generated by Django 2.0.7 on 2018-08-10 06:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20180810_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='hirdate',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 10, 6, 5, 22, 442909, tzinfo=utc)),
        ),
    ]
