# Generated by Django 2.0.7 on 2018-08-10 06:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20180810_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='hirdate',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 10, 6, 6, 48, 479726, tzinfo=utc)),
        ),
    ]
