# Generated by Django 2.0.7 on 2018-08-01 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20180801_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dept',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='user',
            name='job',
            field=models.CharField(max_length=128),
        ),
    ]
