# Generated by Django 2.0.7 on 2018-08-09 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20180801_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='1824399664@qq.com', max_length=64),
        ),
    ]
