# Generated by Django 2.0.7 on 2018-08-10 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20180810_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='hirdate',
            field=models.DateField(auto_now_add=True),
        ),
    ]
